#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

printf "\n\n🏗️👷 Styling and fixing your project before committing\n\n"

# Check Prettier standards
npm run check-format ||
(
    printf "\n\n ❌ Your code styling looks 💩🤢🤮 ❌ 
    Prettier Check Failed. Run npm run format, add changes and try commit again.\n\n";
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
       printf "\n\n❌ Get that weak code out of ELABS code base ❌ \n ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.\n\n"
       false; 
)

# Format files before commiting
npm run format || 
{
    printf "\n\n👷🔨Formatting all the files and adding to staging before commiting.\n\n"
    false;
}

printf "\n\n 🏆 Code looks good! Trying to build now. 🏆"

# If everything passes... Now we can commit
printf "\n\n✅ All check passed. committing the code now. ✅ \n\n"